[package]
name = "majority_element"
version = "0.1.0"
authors = ["Tenji <patricepetit@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name ="majority_element"

[dependencies]
