[package]
name = "longest_common_prefix"
version = "0.1.0"
authors = ["Tenji <patricepetit@hotmail.com>"]
edition = "2018"

[lib]
name="longuest_common_prefix"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
